Hw4 auth
Wiola-D/goit-node-hw2 pull request #3
Opened 2024-07-22 20:03 UTC by Wiola-D

2024-07-23 13:48 UTC, KamilMr requested changes
Hej, 
W lms komentarz do kodu :)

2024-07-25 06:43 UTC, KamilMr approved these changes

2024-07-25 06:43 UTC, KamilMr commented on controllers/contactController.js
> +    console.log(req.user);
tego juz nie potrzeba skoro dziala :)

2024-07-25 17:02 UTC, Wiola-D commented on controllers/contactController.js
> +    console.log(req.user);
jasne :) poprawie

2024-07-25 17:02 UTC, merged